package com.o2o_school.entity;

import java.util.Date;
import java.util.List;

public class Commodity {
    private Integer id;
    private String name;
    private String price;
    private String preferentialPrice;
    private Integer categoryParentId;
    private Integer categoryId;
    private Integer quantity;
    private Integer currQuantity;
    private Integer distributionModel;
    private String deleteFlag;
    private Date createTime;
    private Date updateTime;
    private String description;
    private List<String> imgs;
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.id
     *
     * @param id the value for commodity.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.name
     *
     * @return the value of commodity.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.name
     *
     * @param name the value for commodity.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.price
     *
     * @return the value of commodity.price
     *
     * @mbggenerated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.price
     *
     * @param price the value for commodity.price
     *
     * @mbggenerated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.preferential_price
     *
     * @return the value of commodity.preferential_price
     *
     * @mbggenerated
     */
    public String getPreferentialPrice() {
        return preferentialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.preferential_price
     *
     * @param preferentialPrice the value for commodity.preferential_price
     *
     * @mbggenerated
     */
    public void setPreferentialPrice(String preferentialPrice) {
        this.preferentialPrice = preferentialPrice == null ? null : preferentialPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.category_id
     *
     * @return the value of commodity.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.category_id
     *
     * @param categoryId the value for commodity.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.quantity
     *
     * @return the value of commodity.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.quantity
     *
     * @param quantity the value for commodity.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.curr_quantity
     *
     * @return the value of commodity.curr_quantity
     *
     * @mbggenerated
     */
    public Integer getCurrQuantity() {
        return currQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.curr_quantity
     *
     * @param currQuantity the value for commodity.curr_quantity
     *
     * @mbggenerated
     */
    public void setCurrQuantity(Integer currQuantity) {
        this.currQuantity = currQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.distribution_model
     *
     * @return the value of commodity.distribution_model
     *
     * @mbggenerated
     */
    public Integer getDistributionModel() {
        return distributionModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.distribution_model
     *
     * @param distributionModel the value for commodity.distribution_model
     *
     * @mbggenerated
     */
    public void setDistributionModel(Integer distributionModel) {
        this.distributionModel = distributionModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.delete_flag
     *
     * @return the value of commodity.delete_flag
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.delete_flag
     *
     * @param deleteFlag the value for commodity.delete_flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.create_time
     *
     * @return the value of commodity.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.create_time
     *
     * @param createTime the value for commodity.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.update_time
     *
     * @return the value of commodity.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.update_time
     *
     * @param updateTime the value for commodity.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.description
     *
     * @return the value of commodity.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.description
     *
     * @param description the value for commodity.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

	public Integer getCategoryParentId() {
		return categoryParentId;
	}

	public void setCategoryParentId(Integer categoryParentId) {
		this.categoryParentId = categoryParentId;
	}

	public List<String> getImgs() {
		return imgs;
	}

	public void setImgs(List<String> imgs) {
		this.imgs = imgs;
	}
    
}