package com.o2o_school.entity;

import java.util.Date;

public class CommodityComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_comment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_comment.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_comment.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_comment.rating
     *
     * @mbggenerated
     */
    private String rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_comment.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_comment.append_detail
     *
     * @mbggenerated
     */
    private String appendDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_comment.delete_flag
     *
     * @mbggenerated
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_comment.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_comment.id
     *
     * @return the value of commodity_comment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_comment.id
     *
     * @param id the value for commodity_comment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_comment.user_id
     *
     * @return the value of commodity_comment.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_comment.user_id
     *
     * @param userId the value for commodity_comment.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_comment.commodity_id
     *
     * @return the value of commodity_comment.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_comment.commodity_id
     *
     * @param commodityId the value for commodity_comment.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_comment.rating
     *
     * @return the value of commodity_comment.rating
     *
     * @mbggenerated
     */
    public String getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_comment.rating
     *
     * @param rating the value for commodity_comment.rating
     *
     * @mbggenerated
     */
    public void setRating(String rating) {
        this.rating = rating == null ? null : rating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_comment.detail
     *
     * @return the value of commodity_comment.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_comment.detail
     *
     * @param detail the value for commodity_comment.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_comment.append_detail
     *
     * @return the value of commodity_comment.append_detail
     *
     * @mbggenerated
     */
    public String getAppendDetail() {
        return appendDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_comment.append_detail
     *
     * @param appendDetail the value for commodity_comment.append_detail
     *
     * @mbggenerated
     */
    public void setAppendDetail(String appendDetail) {
        this.appendDetail = appendDetail == null ? null : appendDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_comment.delete_flag
     *
     * @return the value of commodity_comment.delete_flag
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_comment.delete_flag
     *
     * @param deleteFlag the value for commodity_comment.delete_flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_comment.create_time
     *
     * @return the value of commodity_comment.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_comment.create_time
     *
     * @param createTime the value for commodity_comment.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}